In [2]:
# Put these at the top of every notebook, to get automatic reloading and inline plotting
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [3]:
# This file contains all the main external libs we'll use
import fastai
from fastai.imports import *
from fastai.transforms import *
from fastai.conv_learner import *
from fastai.model import *
from fastai.dataset import *
from fastai.sgdr import *
from fastai.plots import *

import torch.nn as nn 
import torch 
import numpy 
%matplotlib inline

from torch.autograd import Variable
from torchvision import models
from fastai import conv_learner
import numpy as np
import matplotlib.pyplot as plt
import skimage.transform

In [58]:
# Parameters for respective architectures
arch1 = resnet34
PATH1 = "../../CHRC_NEW_DATA/chrc_data_patches_norm_1000_dup/"
sz1=512


arch2=resnet50
PATH2 = "../../CHRC_NEW_DATA/chrc_data_patches_norm_duplicated/"
sz2=512

In [59]:
torch.cuda.is_available()

True

In [60]:
torch.backends.cudnn.enabled

True

In [61]:
data1 = ImageClassifierData.from_paths(PATH1, tfms=tfms_from_model(arch1, sz1))
learn1 = ConvLearner.pretrained(arch1, data1, precompute=False)
learn1.precompute = False

In [62]:
data2 = ImageClassifierData.from_paths(PATH2, tfms=tfms_from_model(arch2, sz2))
learn2 = ConvLearner.pretrained(arch2, data2, precompute=False)
learn2.precompute = False

In [63]:
learn1.load('1000x1000_lastlayer_resnet34_lowres_staintools')

RuntimeError: Error(s) in loading state_dict for Sequential:
	Missing key(s) in state_dict: "1.weight", "1.bias", "1.running_mean", "1.running_var", "4.0.conv1.weight", "4.0.bn1.weight", "4.0.bn1.bias", "4.0.bn1.running_mean", "4.0.bn1.running_var", "4.0.conv2.weight", "4.0.bn2.weight", "4.0.bn2.bias", "4.0.bn2.running_mean", "4.0.bn2.running_var", "4.1.conv1.weight", "4.1.bn1.weight", "4.1.bn1.bias", "4.1.bn1.running_mean", "4.1.bn1.running_var", "4.1.conv2.weight", "4.1.bn2.weight", "4.1.bn2.bias", "4.1.bn2.running_mean", "4.1.bn2.running_var", "4.2.conv1.weight", "4.2.bn1.weight", "4.2.bn1.bias", "4.2.bn1.running_mean", "4.2.bn1.running_var", "4.2.conv2.weight", "4.2.bn2.weight", "4.2.bn2.bias", "4.2.bn2.running_mean", "4.2.bn2.running_var", "5.0.conv1.weight", "5.0.bn1.weight", "5.0.bn1.bias", "5.0.bn1.running_mean", "5.0.bn1.running_var", "5.0.conv2.weight", "5.0.bn2.weight", "5.0.bn2.bias", "5.0.bn2.running_mean", "5.0.bn2.running_var", "5.0.downsample.0.weight", "5.0.downsample.1.weight", "5.0.downsample.1.bias", "5.0.downsample.1.running_mean", "5.0.downsample.1.running_var", "5.1.conv1.weight", "5.1.bn1.weight", "5.1.bn1.bias", "5.1.bn1.running_mean", "5.1.bn1.running_var", "5.1.conv2.weight", "5.1.bn2.weight", "5.1.bn2.bias", "5.1.bn2.running_mean", "5.1.bn2.running_var", "5.2.conv1.weight", "5.2.bn1.weight", "5.2.bn1.bias", "5.2.bn1.running_mean", "5.2.bn1.running_var", "5.2.conv2.weight", "5.2.bn2.weight", "5.2.bn2.bias", "5.2.bn2.running_mean", "5.2.bn2.running_var", "5.3.conv1.weight", "5.3.bn1.weight", "5.3.bn1.bias", "5.3.bn1.running_mean", "5.3.bn1.running_var", "5.3.conv2.weight", "5.3.bn2.weight", "5.3.bn2.bias", "5.3.bn2.running_mean", "5.3.bn2.running_var", "6.0.conv1.weight", "6.0.bn1.weight", "6.0.bn1.bias", "6.0.bn1.running_mean", "6.0.bn1.running_var", "6.0.conv2.weight", "6.0.bn2.weight", "6.0.bn2.bias", "6.0.bn2.running_mean", "6.0.bn2.running_var", "6.0.downsample.0.weight", "6.0.downsample.1.weight", "6.0.downsample.1.bias", "6.0.downsample.1.running_mean", "6.0.downsample.1.running_var", "6.1.conv1.weight", "6.1.bn1.weight", "6.1.bn1.bias", "6.1.bn1.running_mean", "6.1.bn1.running_var", "6.1.conv2.weight", "6.1.bn2.weight", "6.1.bn2.bias", "6.1.bn2.running_mean", "6.1.bn2.running_var", "6.2.conv1.weight", "6.2.bn1.weight", "6.2.bn1.bias", "6.2.bn1.running_mean", "6.2.bn1.running_var", "6.2.conv2.weight", "6.2.bn2.weight", "6.2.bn2.bias", "6.2.bn2.running_mean", "6.2.bn2.running_var", "6.3.conv1.weight", "6.3.bn1.weight", "6.3.bn1.bias", "6.3.bn1.running_mean", "6.3.bn1.running_var", "6.3.conv2.weight", "6.3.bn2.weight", "6.3.bn2.bias", "6.3.bn2.running_mean", "6.3.bn2.running_var", "6.4.conv1.weight", "6.4.bn1.weight", "6.4.bn1.bias", "6.4.bn1.running_mean", "6.4.bn1.running_var", "6.4.conv2.weight", "6.4.bn2.weight", "6.4.bn2.bias", "6.4.bn2.running_mean", "6.4.bn2.running_var", "6.5.conv1.weight", "6.5.bn1.weight", "6.5.bn1.bias", "6.5.bn1.running_mean", "6.5.bn1.running_var", "6.5.conv2.weight", "6.5.bn2.weight", "6.5.bn2.bias", "6.5.bn2.running_mean", "6.5.bn2.running_var", "7.0.conv1.weight", "7.0.bn1.weight", "7.0.bn1.bias", "7.0.bn1.running_mean", "7.0.bn1.running_var", "7.0.conv2.weight", "7.0.bn2.weight", "7.0.bn2.bias", "7.0.bn2.running_mean", "7.0.bn2.running_var", "7.0.downsample.0.weight", "7.0.downsample.1.weight", "7.0.downsample.1.bias", "7.0.downsample.1.running_mean", "7.0.downsample.1.running_var", "7.1.conv1.weight", "7.1.bn1.weight", "7.1.bn1.bias", "7.1.bn1.running_mean", "7.1.bn1.running_var", "7.1.conv2.weight", "7.1.bn2.weight", "7.1.bn2.bias", "7.1.bn2.running_mean", "7.1.bn2.running_var", "7.2.conv1.weight", "7.2.bn1.weight", "7.2.bn1.bias", "7.2.bn1.running_mean", "7.2.bn1.running_var", "7.2.conv2.weight", "7.2.bn2.weight", "7.2.bn2.bias", "7.2.bn2.running_mean", "7.2.bn2.running_var", "10.weight", "10.bias", "10.running_mean", "10.running_var", "12.weight", "12.bias", "14.weight", "14.bias", "14.running_mean", "14.running_var", "16.weight", "16.bias". 
	Unexpected key(s) in state_dict: "0.bias", "0.running_mean", "0.running_var", "0.num_batches_tracked", "2.weight", "2.bias", "4.weight", "4.bias", "4.running_mean", "4.running_var", "4.num_batches_tracked", "6.weight", "6.bias". 
	size mismatch for 0.weight: copying a param of torch.Size([64, 3, 7, 7]) from checkpoint, where the shape is torch.Size([1024]) in current model.

In [51]:
learn2.load('resnet50_new_patches_3000_staintools')

In [64]:
learn2.model

Sequential(
  (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU(inplace)
  (3): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (4): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1

In [66]:
class SaveFeatures:
    def __init__(self, m):
        self.handle = m.register_forward_hook(self.hook_fn)
    def hook_fn(self, m, inp, outp):
        self.features = outp
    def remove(self):
        self.handle.remove()

In [67]:
sf = [SaveFeatures(m) for m in [learn2[8], learn2[16]]]

In [76]:
x, y = next(iter(data2.trn_dl))

In [77]:
x.size()

torch.Size([64, 3, 512, 512])

In [78]:
class FeatureSaver:
    def __init__(self, learner, tmp_path, data):
        self.learner = learner
        self.tmp_path = tmp_path
        self.m = learner.models.model
        self.sf = [SaveFeatures(m1) for m1 in [self.m[8], self.m[16]]]
        self.data = data
        self.first_step()
    
    def first_step(self):
        self.m.eval()
        x, y = next(iter(data.trn_dl))
        y = self.m(V(x))
        return
        
    def create_feat_empty_bcolz(self, nf, name):
        return bcolz.carray(np.zeros(nf, np.float32), chunklen=1, mode='w', rootdir=name)

    def get_activations_holder(self, tmpl, nf=None, force=False):
        #tmpl = f'_{self.models.name}_{self.data.sz}.bc'
        names = [os.path.join(self.tmp_path, p+tmpl) for p in ('x_act', 'x_act_val', 'x_act_test')]
        if os.path.exists(names[0]) and not force:
            activations = [bcolz.open(p) for p in names]
        else:
            activations = [self.create_feat_empty_bcolz(nf, n) for n in names]
        return activations

    def save_features_mdl(self, idx, tmpl):
        nf = self.sf[idx].features.shape
#         nf = len(self.sf[idx].features)
        actv = self.get_activations_holder(tmpl, nf, force=True)
        tr_act, val_act, test_act = actv
        if len(actv[0])!=len(self.data.trn_ds):
            self.predict_feat_to_bcolz(idx, self.data.fix_dl, tr_act)
        if len(actv[1])!=len(self.data.val_ds):
            self.predict_feat_to_bcolz(idx, self.data.val_dl, val_act)
        if self.data.test_dl and (len(actv[2])!=len(self.data.test_ds)):
            if self.data.test_dl: self.predict_feat_to_bcolz(idx, self.data.test_dl, test_act)
                
    def predict_feat_to_bcolz(self, idx, gen, arr):
        arr.trim(len(arr))
        lock=threading.Lock()
        self.m.eval()
        print('Starting now')
        for x, _ in tqdm(gen):
            y = self.m(V(x))
            o1 = to_np(self.sf[idx].features)
            with lock:
                arr.append(o1)
                arr.flush()


In [81]:
tmpl = 'x_act_resnet50_0_512.bc'
feat_saver = FeatureSaver(learn2, f'{PATH2}tmp', data2)

In [82]:
feat_saver.save_features_mdl(1, tmpl)

Starting now
100%|██████████| 154/154 [08:21<00:00,  2.32s/it]
Starting now
100%|██████████| 41/41 [02:19<00:00,  2.08s/it]


In [83]:
!ls {PATH2}

models	tmp  train  valid


In [114]:
class ResNet50Bottom(nn.Module):
    def __init__(self, original_model):
        super(ResNet50Bottom, self).__init__()
        self.features = nn.Sequential(*list(original_model.children())[:-8])
        
    def forward(self, x):
        x = self.features(x)
        return x

res50_conv2 = ResNet50Bottom(learn2.model)

In [152]:
i = iter(data2.trn_dl)
inputs, labels = next(i)
inputs, labels = Variable(inputs), Variable(labels)
outputs = res50_conv2(inputs)

In [110]:
len(data2.trn_dl.dataset.fnames)

9819

In [120]:
outputs.shape

torch.Size([64, 4096])

In [154]:
outputs[1]

tensor([1.5471, 1.9567, 1.4873,  ..., 0.2694, 0.1216, 0.3571], device='cuda:0')

In [122]:
inputs, labels = next(i)
inputs, labels = Variable(inputs), Variable(labels)
outputs = res50_conv2(inputs)
outputs[0]

tensor([0.8885, 3.4051, 1.9177,  ..., 0.5425, 0.2665, 0.6057], device='cuda:0')

In [132]:
i.send()

TypeError: send() takes exactly one argument (0 given)

In [ ]:
i = iter(data2.trn_dl)

In [168]:
res50_conv2(Variable(V(data2.trn_dl.get_batch([9818])[0])))

RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 7, 7], but got input of size [3, 512, 512] instead

In [176]:
np.array(data2.trn_dl.dataset.get1item(12)[0])

array([[[ 1.65136,  1.59942,  1.43624, ...,  0.93642,  1.17164,  0.75017],
        [ 1.38131,  1.41287,  1.16173, ...,  0.94259,  0.8877 ,  0.11419],
        [ 1.2332 ,  1.11449,  1.39986, ...,  0.73916,  0.68656,  0.19979],
        ...,
        [ 2.23416,  2.23951,  2.22591, ...,  2.23541,  2.23908,  2.22926],
        [ 2.22168,  2.23207,  2.22627, ...,  2.23016,  2.23426,  2.22651],
        [ 2.22473,  2.22475,  2.23496, ...,  2.23063,  2.22432,  2.23869]],

       [[ 0.9711 ,  0.93752,  0.5783 , ..., -0.31907,  0.08526, -0.34831],
        [ 0.45204,  0.40131,  0.08633, ..., -0.32827, -0.38344, -1.0391 ],
        [ 0.16897,  0.02024,  0.54729, ..., -0.57599, -0.60046, -1.01487],
        ...,
        [ 2.41349,  2.41896,  2.40506, ...,  2.41477,  2.41852,  2.40848],
        [ 2.40074,  2.41136,  2.40279, ...,  2.4094 ,  2.41046,  2.39499],
        [ 2.40386,  2.40387,  2.40569, ...,  2.40989,  2.39188,  2.38945]],

       [[ 2.14987,  2.10124,  1.96512, ...,  1.58498,  1.80771,  1.100

In [174]:
data2.trn_dl.get_batch([12])[0]

array([[[[ 1.65136,  1.59942,  1.43624, ...,  0.93642,  1.17164,  0.75017],
         [ 1.38131,  1.41287,  1.16173, ...,  0.94259,  0.8877 ,  0.11419],
         [ 1.2332 ,  1.11449,  1.39986, ...,  0.73916,  0.68656,  0.19979],
         ...,
         [ 2.23416,  2.23951,  2.22591, ...,  2.23541,  2.23908,  2.22926],
         [ 2.22168,  2.23207,  2.22627, ...,  2.23016,  2.23426,  2.22651],
         [ 2.22473,  2.22475,  2.23496, ...,  2.23063,  2.22432,  2.23869]],

        [[ 0.9711 ,  0.93752,  0.5783 , ..., -0.31907,  0.08526, -0.34831],
         [ 0.45204,  0.40131,  0.08633, ..., -0.32827, -0.38344, -1.0391 ],
         [ 0.16897,  0.02024,  0.54729, ..., -0.57599, -0.60046, -1.01487],
         ...,
         [ 2.41349,  2.41896,  2.40506, ...,  2.41477,  2.41852,  2.40848],
         [ 2.40074,  2.41136,  2.40279, ...,  2.4094 ,  2.41046,  2.39499],
         [ 2.40386,  2.40387,  2.40569, ...,  2.40989,  2.39188,  2.38945]],

        [[ 2.14987,  2.10124,  1.96512, ...,  1.58498,  